### ISSUE TITLE
Can't Starting server

### ISSUE THREAD

**Issue by Packae** [SoulGirlJP/AzureV316#12]
```
/* Socket Configuration and Server Up */
[오류] 서버 세팅파일을 불러오는데 실패하였습니다.
java.io.FileNotFoundException: property\ServerSettings.properties (指定されたパスが見つかりません。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at constants.ServerConstants.<clinit>(ServerConstants.java:151)
	at launcher.ServerPortInitialize.LoginServer.<clinit>(LoginServer.java:34)
	at launcher.Start.main(Start.java:110)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at launcher.ServerPortInitialize.LoginServer.run_startup_configurations(LoginServer.java:82)
	at launcher.Start.main(Start.java:110)
Caused by: java.lang.NullPointerException
	at provider.WzXML.XMLWZFile.fillMapleDataEntitys(XMLWZFile.java:24)
	at provider.WzXML.XMLWZFile.<init>(XMLWZFile.java:20)
	at provider.MapleDataProviderFactory.getWZ(MapleDataProviderFactory.java:15)
	at provider.MapleDataProviderFactory.getDataProvider(MapleDataProviderFactory.java:21)
	at launcher.LauncherHandlers.MapleLoginHelper.<init>(MapleLoginHelper.java:25)
	at launcher.LauncherHandlers.MapleLoginHelper.<clinit>(MapleLoginHelper.java:15)
	... 2 more
java.lang.NumberFormatException: For input string: "20200909104123.0"
```

**Comment by KOOKIIEStudios** [comment]
Gentle reminder to either enclose in code blocks, or use a screenshot.
Can you double check that all files are properly downloaded, and the server settings file(s) are properly set?

**Comment by Packae** [comment]
oh, sorry I take a screenshot 
hmm properly maybe.
![無題](https://user-images.githubusercontent.com/75624919/101365511-40299580-38e7-11eb-9975-58cb0ce11e8d.jpg)

**Comment by KOOKIIEStudios** [comment]
So the [*property*](https://github.com/SoulGirlJP/AzureV316/tree/master/AzureMS/property) folder is properly downloaded?
Especially the [*ServerSettings.properties*](https://github.com/SoulGirlJP/AzureV316/blob/master/AzureMS/property/ServerSettings.properties) file:
**AzureV316/AzureMS/property/ServerSettings.properties**
Could you try cloning/pulling again, and checking if the [*ServerSettings.properties*](https://github.com/SoulGirlJP/AzureV316/blob/master/AzureMS/property/ServerSettings.properties) file is properly located?

(Also, gentle reminder that you will need to set the locale to Korean later, if you want to run the client. I believe yours is set to Japanese now?)

**Comment by Packae** [comment]
I think properties file is properly located.
hmm, I was change system locale to Korea I don't know why : (
![無題](https://user-images.githubusercontent.com/75624919/101369792-0e66fd80-38ec-11eb-9371-853a4e026dc6.jpg)

**Comment by KOOKIIEStudios** [comment]
That's strange. @Bratah123 any ideas?

Edit: noted from your timestamp details that it is already set to Korean locale (with Japanese system language), so that should be fine/properly set already.

**Comment by Packae** [comment]
and could you check this please?
is this correctly? : (
![1](https://user-images.githubusercontent.com/75624919/101370901-75d17d00-38ed-11eb-813a-b4a53054c723.jpg)
![2](https://user-images.githubusercontent.com/75624919/101370907-7833d700-38ed-11eb-9a1c-2f05c11042e4.jpg)

**Comment by KOOKIIEStudios** [comment]
JDK is fine, I saw the JDK mentioned in  the console readout already, that's why I didn't comment.
You're still getting the same error messages now?

**Comment by Packae** [comment]
hmm yes;;;
There was no error when I set this to the full path, will be works in that case? 
like this.
```
FileInputStream("C:/Users/blue/Desktop/AzureV316/AzureMS/property/ServerSettings.properties");
```

**Comment by KOOKIIEStudios** [comment]
can you try setting the working directory to:
***C:\Users\blue\Desktop\AzureV316\AzureMS***

My best guess is that because you set the working directory to *AzureV316\AzureMS\src\launcher*, it can't find the properties file via the *property\ServerSettings.properties* relative path.

### Reference:
![image](https://user-images.githubusercontent.com/25145447/101374064-abc03280-38e8-11eb-9604-9d986c6e506b.png)
Run -> Edit Configurations

**Comment by Packae** [comment]
oh!! this is errors...?
![po](https://user-images.githubusercontent.com/75624919/101374891-188bfa80-38f2-11eb-9642-b13c3fef1048.jpg)

**Comment by KOOKIIEStudios** [comment]
Don't worry, those aren't fatal errors. It just found extra files it doesn't need. Soul probably tried running it with a bunch of different JDKs before, that's why there's so many slf4j. (This is why Me/Brandon/Desc have advocated for Maven management 😒)

The fact that you can get the channels to load means it's good to go. You should be able to run a client and get into game now.

**Comment by KOOKIIEStudios** [comment]
Flagging for closing since this issue seems resolved.

**Comment by Packae** [comment]
thank you so much, could I ask other things?
TAIGA_Redirector.exe is not work, I don't know why Firewall or untivirus somthing?
If you know please teach me : (

**Comment by KOOKIIEStudios** [comment]
That might be out of the scope of this project (and there's not enough details to tell from your description).
Might want to divert that to Soul on Discord (in Azure #help) since he's the only one who has access to the source for that redirector. This open source project is only concerned with the server side.

Just a gentle reminder that the redirector is for localhost only - you can't connect from a different machine than the one the server is hosted on.

**Comment by Packae** [comment]
I'm sorry working!
thank you so much so many use time for me!
have a nice day!

**Comment by KOOKIIEStudios** [comment]
No problem
