### ISSUE TITLE
Windows 11 is very laged on redirector

### ISSUE THREAD

**Issue by Dalk2ness** [SoulGirlJP/AzureV316#17]
localhost Mapleexploere is very lag how can i fixed?

**Comment by KOOKIIEStudios** [comment]
Since you mentioned re-director/localhost (sic), I assume you are referring to the client side - more specifically, the provided test client.
I will assume that you are using a machine that is powerful enough to handle both the server and client at the same time (since that client is local host-only) - otherwise the advice would be to invest in more powerful hardware.

The experience wasn't exactly buttery smooth even on Windows 10, so I'm not sure if it's an issue specific to Windows 11. I would love to check if that's the case, but I don't have a Windows 11 test bench on hand.
If it's specific to Windows 11, and the problem is indeed client-sided, then I'm afraid there's nothing you can really do since this is a private server emulator - the game client is the same client published by NEXON. That is unless you would like to de-obfuscate & unpack the client, fix the issues in the client, and re-pack the client - a feat that not only requires a lot of expertise, but is also not really worth the time and effort to perform. If the problem is server-sided, the solution would be to optimise the server further. There are many areas of the source code that can be further optimised. This would have to be done on your own, though, because IIRC, this project has been deprecated by SoulGirlJP about a year or so ago. Perhaps you can try reaching SoulGirlJP on Discord directly, or try some of the forks like [Electron](https://github.com/Bratah123/ElectronMS) instead, if you're unable or unwilling to perform modifications on your own.

(Also, AFAIK, that client is not actually part of the project and was sourced from an external party, and as such would not be supported by the project team anyway.)

---

#### For reference:
- *The owner's new Discord handle post-apocalypse (Discord mass-banning MSPS devs): `SoulsJP#3857`*
- *The owner's development studio: [Indoors Studio](https://discord.gg/wJrbW8CK)*
