### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xtristann** [SoulGirlJP/AzureV316#2]
![image](https://user-images.githubusercontent.com/71190848/93002659-16243980-f56b-11ea-9586-933c967c89bd.png)

Please help unable to build with multiple errors

**Comment by SoulGirlJP** [comment]
Setup your unicode to the project to x-window-949

**Comment by xtristann** [comment]
Thanks! But i have another error 
![image](https://user-images.githubusercontent.com/71190848/93012034-48678280-f5cf-11ea-8438-599c1c73ac67.png)

**Comment by xtristann** [comment]
![image](https://user-images.githubusercontent.com/71190848/93012040-574e3500-f5cf-11ea-90ad-4aa0470cfc14.png)

**Comment by xtristann** [comment]
![image](https://user-images.githubusercontent.com/71190848/93012350-579bff80-f5d2-11ea-8958-e071ce247498.png)
Thanks! But I have another error

**Comment by KOOKIIEStudios** [comment]
I doubt that's a related issue. :o
You may wanna double check your database for this one

**Comment by xtristann** [comment]
nothing wrong with the database though, i set the data in lastlogin null and the error for the out of range error disappeared but the  error in red still persist.

**Comment by KOOKIIEStudios** [comment]
yeah, you ss-ed the chunk, and that was the first line so I thought the out of range was what you wanted to fix.
I can't replicate the NPE - your wz folder is populated and accessible right?
Since NPEs are generic, I can't say for certain. But considering that line 24 of the XMLWZFile class is a `for` loop (`for (File file : lroot.listFiles())`), and an emply `lroot` could cause the `listFiles()` method to throw a NPE, I would check the wz folder just to rule that out.

**Comment by xtristann** [comment]
thanks i will try to re dump the wz file

**Comment by KOOKIIEStudios** [comment]
@Bratah123 flag for closing?

**Comment by Bratah123** [comment]
Closed, original error was the encoding!

**Comment by xtristann** [comment]
the wz file error isnt fixed yet lol there is 2 issues
